export const ADD_ITEM_TO_CART:String = "ADD_ITEM_TO_CART";
export const REMOVE_ITEM_FROM_CART:String = "REMOVE_ITEM_FROM_CART";
export const REMOVE_ALL_ITEM_FROM_CART:String = "REMOVE_ALL_ITEM_FROM_CART";
export const REMOVE_ALL_CART:String = "REMOVE_ALL_CART";
